version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: casa-aperto-db
    environment:
      POSTGRES_USER: casaaperto
      POSTGRES_PASSWORD: casaaperto
      POSTGRES_DB: casa_aperto
    ports:
      - '5432:5432'
    volumes:
      - casa_aperto_data:/var/lib/postgresql/data

volumes:
  casa_aperto_data:
